# Generated by Django 5.0.1 on 2024-02-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchlist', to='auctions.listing'),
        ),
    ]
