# Generated by Django 5.0.1 on 2024-02-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_user_bid_user_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bid',
            field=models.IntegerField(default=0),
        ),
    ]
