# Generated by Django 5.0.1 on 2024-02-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_user_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bid',
        ),
    ]
