# Generated by Django 5.0.1 on 2024-02-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_bid_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.IntegerField(),
        ),
    ]
