# Generated by Django 5.0.1 on 2024-02-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_user_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='user',
        ),
    ]
