# Generated by Django 5.0.1 on 2024-02-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_remove_bid_bid_remove_bid_listing_remove_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.IntegerField(default=0),
        ),
    ]
