# Generated by Django 5.0.1 on 2024-02-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0040_alter_bid_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid',
        ),
    ]
