# Generated by Django 5.0.1 on 2024-02-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0044_alter_bids_bid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bids',
        ),
    ]
