# Generated by Django 5.0.1 on 2024-02-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0047_rename_bids_bid_rename_watchlist_user_userwatchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userWatchlist',
            field=models.ManyToManyField(blank=True, related_name='userWatchlist', to='auctions.listing'),
        ),
    ]
