# Generated by Django 5.0.1 on 2024-03-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0051_alter_bids_listing_alter_listing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=520),
        ),
    ]
