# Generated by Django 5.0.1 on 2024-03-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0053_alter_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(default='', max_length=600),
        ),
    ]
